export const SPLASH_SCREEN = 'SPLASH_SCREEN'
export const HOME_SCREEN = 'HOME_SCREEN'
export const CATEGORY_SCREEN = 'CATEGORY_SCREEN'
export const ANALYTICS_SCREEN = 'ANALYTICS_SCREEN'
export const SETTING_CONTAINER = 'SETTING_CONTAINER'
export const ADDTRANSACTION_CONTAINER = 'ADDTRANSACTION_CONTAINER'


